:seedling: Hot Reload for secrets
syself/hetzner-cloud-controller-manager pull request #49
Opened 2024-12-13 09:11 UTC by guettli

When the secrets are provided via a mounted secret, then the ccm will reload the secrets automatically.

The mounted secret needs to be in etc/hetzner-secret

2024-12-16 09:47 UTC, janiskemper requested changes

2024-12-16 09:47 UTC, janiskemper commented on .github/workflows/ci.yml
> -# ---
can you plz separate this in a clean up PR? Otherwise it is hard to review

2024-12-16 09:47 UTC, janiskemper commented on go.mod
> +go 1.23.0
I wouldn't update to go 1.23 yet maybe. Are you sure? Anyway, I would also do it in a separate PR, together with the upgrades of the modules

2024-12-16 09:47 UTC, janiskemper commented on hcloud/cloud.go
> -	nodeName := os.Getenv(nodeNameENVVar)
what did you do to replace this? I don't see it

2024-12-16 09:47 UTC, janiskemper commented on internal/hotreload/hotreload.go
> +	return event.Op&fsnotify.Write == fsnotify.Write
is this & correct? It also looks like it's not gofumpted

2024-12-16 09:47 UTC, janiskemper commented on internal/hotreload/hotreload.go
> +var (
you should rather define them on top

2024-12-16 09:47 UTC, janiskemper commented on internal/hotreload/hotreload.go
> +	HcloudTokenReloadCounter uint64
is this only for testing? If so, you should clearly explain why you have this

2024-12-16 09:47 UTC, janiskemper commented on internal/hotreload/hotreload.go
> +	oldRobotUser       string
I didn't understand why you have this

2024-12-16 09:47 UTC, janiskemper commented on internal/robot/client/cache/client.go
> +	c.m = nil
can you comment these little details? This is extremely important but easy to not see

2024-12-16 09:59 UTC, guettli commented on hcloud/cloud.go
> -	nodeName := os.Getenv(nodeNameENVVar)
@janiskemper the nodeName was never used. It was removed in upstream, too.

2024-12-16 20:27 UTC, janiskemper requested changes

2024-12-17 08:58 UTC, guettli commented on hcloud/cloud.go
> +	robotClient, err := cache.NewCachedRobotClient(rootDir, httpClient, "")
I added a comment and logging.

2024-12-17 09:11 UTC, guettli commented on internal/hotreload/hotreload.go
> +		return fmt.Errorf("reading robot credentials from secret: %w", err)
I think returning an error is enough here. The error will be logged by the caller. Please mention it again, if it is important for you, and I will add logging.

2024-12-17 09:36 UTC, guettli commented on hcloud/cloud.go
> +	secretDir := filepath.Join(rootDir, "etc", "hetzner-secret")
@janiskemper the string was used in several places. I aligned the naming and created a function to get the directory: hotreload.CredentialsDirectory(rootDir). ok now?

2024-12-17 09:42 UTC, guettli commented on internal/hotreload/hotreload.go
> +package hotreload
ok, I renamed the package to `credentials`. I took the plural because it handles several crendentials. ok?

2024-12-17 09:48 UTC, guettli commented on internal/hotreload/hotreload.go
> +	oldRobotUser     string
yes, this makes sense. But maybe it is better to do that later. There are some other important topics on my list.

I created an issue: https://github.com/syself/hetzner-cloud-controller-manager/issues/57

Is that ok for you?

2024-12-17 10:01 UTC, guettli commented on internal/hotreload/hotreload.go
> +func loadRobotCredentials(hetznerSecretDirectory string, robotClient robotclient.Client) error {
done

2024-12-17 10:01 UTC, guettli commented on internal/robot/client/cache/client.go
> +	secretsDir := filepath.Join(rootDir, "etc", "hetzner-secret")
The function is called `credentials.GetDirectory(rootDir)`. ok?

2024-12-17 10:07 UTC, janiskemper commented on internal/hotreload/hotreload.go
> +		return fmt.Errorf("reading robot credentials from secret: %w", err)
I was just referring to the error message, not a separate log ;)

2024-12-17 10:08 UTC, guettli commented on internal/robot/client/cache/client.go
> +func NewClient(robotClient hrobot.RobotClient, cacheTimeout time.Duration) robotclient.Client {
It got used in one place. But this was in the same package. I inlined the function. While doing that I noticed that we have a global variable `handler` that could easily be made a normal variable.

2024-12-17 10:09 UTC, janiskemper commented on internal/hotreload/hotreload.go
> +package hotreload
AFAIK singular names are the general rule, but I don't mind here

2024-12-17 10:09 UTC, janiskemper commented on hcloud/cloud.go
> +	secretDir := filepath.Join(rootDir, "etc", "hetzner-secret")
yes

2024-12-17 10:29 UTC, guettli commented on internal/hotreload/hotreload.go
> +		return fmt.Errorf("reading robot credentials from secret: %w", err)
ok, I see. I added "failed" to the error messages.

2024-12-17 13:09 UTC, merged

2024-12-17 13:12 UTC, janiskemper commented on internal/robot/client/cache/client.go
> +func NewClient(robotClient hrobot.RobotClient, cacheTimeout time.Duration) robotclient.Client {
I think that we did it differently in CAPH, probably because of testing. This might not be relevant here, but make sure that this doesn't actually destroy anything

2024-12-17 13:40 UTC, guettli commented on internal/robot/client/cache/client.go
> +func NewClient(robotClient hrobot.RobotClient, cacheTimeout time.Duration) robotclient.Client {
I had a look before removing the global variable `handler`. It was used only at one place.

2024-12-18 10:24 UTC, guettli commented on internal/hotreload/hotreload.go
> +			case event := <-watcher.Events:
I added some empty lines, and created a function for the handling of the event, to make it easier to read.

2024-12-18 10:27 UTC, guettli commented on internal/hotreload/hotreload.go
> +				case "robot-password":
If one file is missing, there will be in error in that function:

```go
func readRobotCredentials(credentialsDir string) (username, password string, err error) {
	robotUserNameFile := filepath.Join(credentialsDir, "robot-user")
	robotPasswordFile := filepath.Join(credentialsDir, "robot-password")

	u, err := os.ReadFile(robotUserNameFile)
	if err != nil {
		return "", "", fmt.Errorf("reading robot user name from %q failed: %w", robotUserNameFile, err)
	}

	p, err := os.ReadFile(robotPasswordFile)
	if err != nil {
		return "", "", fmt.Errorf("reading robot password from %q failed: %w", robotPasswordFile, err)
	}

	return strings.TrimSpace(string(u)), strings.TrimSpace(string(p)), nil
}
```

This case is already handled.

Or am I missing something?

2024-12-18 10:31 UTC, guettli commented on internal/hotreload/hotreload.go
> +				klog.Infof("error: %s", err)
I extended this:

```
klog.Infof("error from fsnotify file watcher of %q: %s", credentialsDir, err)
```

2024-12-18 10:32 UTC, guettli commented on internal/hotreload/hotreload.go
> +				case "robot-user":
done